# syntax=docker/dockerfile:1.3
FROM python:3.9-slim

WORKDIR /restack
COPY restack/ .

WORKDIR /app

COPY backend/ .

# Install dependencies in one layer to leverage caching
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "backend.py"]