# syntax=docker/dockerfile:1.3
FROM python:3.9-slim

WORKDIR /restack
COPY restack/ .

WORKDIR /app

COPY frontend/ .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

# CMD ["tail", "-f", "/dev/null"]
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]